### ISSUE TITLE
Writing an Environment

### ISSUE THREAD

**Issue by cynthiatliu** [rllab/rllab#32]
Hi,

Background: I am an rising freshman undergraduate, and I am doing a research internship this summer in reinforcement learning and its application to crystallography. Specifically, I hope to write an environment compatible with ddpg for conducting experiments, so after training upon thousands of episodes the machines could accurately calculate a "UB matrix" using the fewest measurements.

Just one question:
1. I noticed that your algorithm includes fixed action (control) types. For training, actions are usually just selecting a reflection -- possible reflections are calculated and stored in an array, and the algorithm simply chooses one. However, if a peak is not found (if the observation is below a "background" threshold) then the action becomes a scan across two dimensions. Here, the program selects the coordinates on which to measure, and the coordinates are chosen from a continuum. Is such an action selection scheme possible in your framework, and how should I write this?

Thanks!!

**Comment by dementrock** [comment]
Hi @cynthiatliu, sorry but I don't totally understand your setup. Do you mean that the action is either a discrete choice (1 out of N), or a two-dimensional continuous number?

You will probably need to implement a new action type, similar to how they are defined right now:

- https://github.com/rllab/rllab/blob/master/rllab/spaces/discrete.py
- https://github.com/rllab/rllab/blob/master/rllab/spaces/box.py
- https://github.com/rllab/rllab/blob/master/rllab/spaces/product.py

Your scenario is more like a union type rather than a product type. Since you need to be able to convert to/from a vector representation (see `flatten` and `unflatten`), one possible scheme is that you use the first entry in the vector to denote whether the action is a discrete choice or a 2D vector. The subsequent entries encode the actual choice.

**Comment by cynthiatliu** [comment]
Yes, that's what I mean. And thanks! I'll work on it.

**Comment by cynthiatliu** [comment]
Hi,

For this action space, how should the method "new_tensor_variables" be overwritten? Thanks,

**Comment by dementrock** [comment]
Depending on your representation. If it's either a discrete or a 1D vector, you can use the same code as the `Box` type: https://github.com/rllab/rllab/blob/master/rllab/spaces/box.py#L71

**Comment by cynthiatliu** [comment]
It's either a discrete or a 2D vector.

**Comment by cynthiatliu** [comment]
Solved the problems :+1: Thanks!
