### ISSUE TITLE
More complex neural nets

### ISSUE THREAD

**Issue by TheBirdie** [rllab/rllab#8]
Hello,

I did not find any "non-hackish" way to implement custom complex Neural Net architectures in RLLab.
For example, it could be interesting to be able to do the following:
- Use convolutional neural nets to process images as input (there is already a class for that in RLLab, but the GaussionMLPPolicy does not offer this option for example)
- These CNN possibly need a pre-training (as auto-encoders for example), and should not be completely encapsulated inside the policy

I started implementing a draft of this for the Gaussian MPL Policy here:
https://github.com/TheBirdie/rllab/commit/9d623ee2521c0b7462f8c8413662e7a73d235b18
It does not required deep changes in the policy code, and yet allows more flexibility.

A second step could be to have more flexibility regarding the policy input (observation) shape.

For example, one may be willing to observe several kinds of data, with a different processing for each:
- An image processing with a CNN
- Other data processed with classical fully connected Neural Nets
However, I did not find any possibility to split the inputs nicely. Currently, the policy receives a flatten array with all the information concatenated.
Is that something that sounds interesting?

Thank you

**Comment by dementrock** [comment]
Hi @TheBirdie, thanks for your suggestions! We will update the interface of the policy so that it can optionally take a customized network, which should be closer to the interface we have for categorical policy, as shown here: https://github.com/rllab/rllab/blob/master/rllab/policies/categorical_mlp_policy.py

For splitting the inputs, there is a method on space instances called `unflatten` and a batched version called `unflatten_n`, which could be found e.g. here:
- https://github.com/rllab/rllab/blob/master/rllab/spaces/box.py#L57
- https://github.com/rllab/rllab/blob/master/rllab/spaces/product.py#L45

Are these similar to what you are looking for?

**Comment by dementrock** [comment]
I just pushed a commit with the aforementioned updates to the policy interface:

https://github.com/rllab/rllab/commit/bc1b5060e3bba3c70ab67a0cff0f4398ebb09717

**Comment by TheBirdie** [comment]
Awesome! It looks exactly like what I was looking for.
Thank you very much for the work/support @dementrock!
